// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Samir_Cabrera.Movies.Data;

namespace Samir_Cabrera.Movies.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20210604170513_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13");

            modelBuilder.Entity("Samir_Cabrera.Movies.Entity.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            MovieId = 2,
                            Url = "s"
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 2,
                            Url = "s"
                        },
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            Url = "s"
                        });
                });

            modelBuilder.Entity("Samir_Cabrera.Movies.Entity.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Like")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ToViewLater")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("View")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "http://sample.com",
                            Like = true,
                            Title = "s",
                            ToViewLater = false,
                            View = false
                        },
                        new
                        {
                            Id = 2,
                            Description = "http://sample.com",
                            Like = true,
                            Title = "s",
                            ToViewLater = false,
                            View = false
                        });
                });

            modelBuilder.Entity("Samir_Cabrera.Movies.Entity.Image", b =>
                {
                    b.HasOne("Samir_Cabrera.Movies.Entity.Movie", null)
                        .WithMany("Images")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
